drf_extra_fields/fields.py

Python 2 utilizes basestring. Python 3 removed basestring
and utilizes str. Using the major number of the Python
version, string_type is defined accordingly.

Add string type resolution from Python version (to support Python 2 and Python 3)

---

drf_extra_fields/fields.py

By not overwriting it, the standard behaviour of `use_url` /
`UPLOADED_FILES_USE_URL` will be kept.  This will then also match the
behaviour described in the comment - where the URL is meant to be
returned instead of the name.

Base64ImageField: do not override to_representation

---

README.md
drf_extra_fields/fields.py
tests/test_fields.py

The Base64ImageField will now allow the optional behaviour of serialising modelImage fields into base64. This will only work if represent_in_base64 is explicitly set to True, otherwise the default behaviour will remain.

Optional Base64 Image downloads.

---

README.md
drf_extra_fields/fields.py
tests/test_fields.py

The motivation for this PR is that it makes it easier for API clients to use.

strip base64 header if it's present

---

drf_extra_fields/fields.py

Small change to prevent an exception being thrown for missing StandardError under Python 3

Fix for Python 3 (removed StandardError)

---

drf_extra_fields/relations.py

In html view of DRF, ``get_choices()`` is called to get the choices.
As we have override ``to_representation()`` and it returns a ``dictionary`` instead of ``pk``, the html view raise errors.
So override the ``get_choices()`` function in order to return the ``pk`` value list

Fixing PresentablePrimaryKeyRelatedField to show in html view

---

setup.py

The python 3 classifier is required to list the package in the "Python 3" list on PyPI.
Also this tool: https://github.com/brettcannon/caniusepython3 uses the classifier to check for python 3 support for a package

Add python 3 trove classifier

---

.gitignore
.travis.yml
drf_extra_fields/fields.py
tests/test_fields.py
tox.ini

I found it handy to support a fallback of using the base DRF Image to_internal_value to handle form uploads in addition to Base64 encoded JSON, so I made hyrbrid versions

Added fallback support to Base64ImageField for regular ImageType/multipart

---

drf_extra_fields/fields.py

Some malformed client sent some garbage input which resulted in this error. Base64ImageField should handle this gracefully. The base64.py raises a UnicodeEncodeError, which then throws a ValueError which `drf-extra-fields` should handle (https://github.com/python/cpython/blob/master/Lib/base64.py#L39).
Here's the full stack trace.
```
Traceback (most recent call last):
File "/app/.heroku/python/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/app/.heroku/python/lib/python3.6/contextlib.py", line 53, in inner
return func(*args, **kwds)
File "/app/.heroku/python/lib/python3.6/site-packages/newrelic/hooks/framework_django.py", line 544, in wrapper
return wrapped(*args, …
```

Handle ValueError in Base64ImageField

---

README.md
drf_extra_fields/geo_fields.py
tests/test_fields.py

This pull request contains the changes necessary in order for the values of the `PointField` to be serialized as `float` when serializing to json.
Existing Issue: https://github.com/Hipo/drf-extra-fields/issues/38

Float output for PointField

---

README.md

I fixed the mistakenly given argument `User.objects` (a manager) to `User.objects.all()` (a queryset).

Fix manager to queryset in README

---

.travis.yml

`dist: xenial` is needed for Python 3.7: https://github.com/travis-ci/travis-ci/issues/9815

Support Python 3.7

---

drf_extra_fields/fields.py

This allows its default implementation to be overridden. I needed to implement this in my project so I could preserve the original file name (I also took extra precautions to prevent filename collision by putting them in unique directories). I didn't find much online from other people trying to do this, so perhaps my use-case is unusual.

Moved filename generation of Base64FieldMixin into a method.

---

drf_extra_fields/fields.py

When this error is returned, it is not very clear about the fact that error is actually a type error (the fact that the input is not a `str`). The current error seems to imply that the value is not "base64 encoded" correctly.

Improve error message when base64 data is an invalid type

---

drf_extra_fields/fields.py
tests/test_fields.py

There is a [bug](https://bugs.python.org/issue16512) in python's imghdr module. It does not recognize some valid `jpeg` files like [this](https://picsum.photos/500/500/?image=705). drf-extra-fields is using this module to check file types which fails for some images. I have replaced type checking functionality with PIL.

Replaced buggy imghdr with PIL

---

setup.py

[License](https://github.com/Hipo/drf-extra-fields/blob/master/LICENSE) file states `Apache 2.0`. However, `setup.py` states the `BSD` license.

License is replaced with Apache 2.0

---

README.md
drf_extra_fields/relations.py

I have numerous additional extensions to my serializers and need the ability to pass in arbitrary keyword arguments to limit the fields returned, etc.

Pass in arbitrary arguments to PresentationSerializer

---

.gitignore
drf_extra_fields/fields.py

Random names generated by drf-extra-fields include file names that end with -ad0, which is blocked by ublock origin and possibly other adblockers. 
See https://github.com/Hipo/drf-extra-fields/issues/94 and the [StackOverflow issue by me](https://stackoverflow.com/questions/57227131/images-that-fit-the-regexp-ad0-9-png-can-not-be-loaded-in-any-browser/57227395#57227395).

Increase random file name length by 1 to avoid adblocker trigger

---

drf_extra_fields/fields.py

There is no real benefit in keeping it short.

Use full uuid4 in Base64FieldMixin.get_file_name()

---

tox.ini

How did this work with that typo? :slightly_smiling_face:

Add missing space to dependency definition

---

.travis.yml
drf_extra_fields/compat.py
drf_extra_fields/fields.py
drf_extra_fields/geo_fields.py
tox.ini

Fix #115 by moving `text_type` and `string_types` imports in the `compat` module.

support Django 3.0

---

MANIFEST.in
setup.py

Currently [pip-licenses](https://github.com/raimon49/pip-licenses) can't include the LICENSE file for this project because the correct metadata is not setup.
This PR sets up the metadata correctly so the LICENSE file is properly included/linked to in source and wheel distributions.

Add LICENSE file metadata to packaged distributions

---

drf_extra_fields/fields.py
setup.py
tests/test_fields.py

Issue: https://github.com/Hipo/drf-extra-fields/issues/109
The exception catches both `OSError` and `IOError` because `Python3` raises and `OSError` and `Python2` raises an `IOError`.
- Invalid Base64 image inputs are handled.
- Test for invalid Base64 image inputs are implemented.
- Error messages in tests are now being taken from related Field classes.
- Version is bumped from `2.0.0` to `2.0.1`

Handle invalid Base64 inputs in Base64ImageField

---

drf_extra_fields/fields.py
drf_extra_fields/geo_fields.py

This alias is only needed for python2 support, and is deprecated as of
django 4.0
https://docs.djangoproject.com/en/3.0/releases/3.0/#id3
Django's last LTS with python2 compatibility ends its extended support
in April 2020.
https://www.djangoproject.com/download/

Stop using deprecated ugettext alias

---

requirements_dev.txt
setup.py

Closes #126 
[Pillow 6.2.1 is 6 months old](https://pypi.org/project/Pillow/6.2.1/).
Users can still pin `Pillow` if they wish, using `requirements.txt`, `pip-tools`, `poetry`, `pipenv`, etc.

Allow install of new versions of Pillow

---

README.md
drf_extra_fields/geo_fields.py
tests/test_fields.py

Allow to set a SRID on the Point object created by the PointField serializer.
This is needed since Django requires SRID to be set since https://github.com/django/django/commit/bde86ce9ae17ee52aa5be9b74b64422f5219530d

Add SRID attribute to PointField.

---

README.md

Add sample workaround code on Base64ImageField, Base64FileField to correct the swagger generated document of drf-yasg project.

Fix base64field on drf-yasg

---

drf_extra_fields/fields.py
tests/test_fields.py

Related issue: #117 
Non-primitive types such as `DateRange` are not allowed in `initial` field in range fields. By overriding `get_initial` method handles this problem.

Allow non-primitive values in "initial" field in range fields

---

README.md
drf_extra_fields/relations.py
tests/test_relations.py
tests/utils.py

With this parameter and GET request, serializer field response to read_source parameter. For instance
`PresentablePrimaryKeyRelatedField(read_source="x_property", .......)`
will behave normally on not GET request but on GET request, it will use models "x_property"
related issue: #136

Add read_source parameter on PresentablePrimaryKeyField

---

README.md
drf_extra_fields/relations.py
tests/test_relations.py

#128
Add support for recursive field with `presentation_serializer="self"`.
Does not support `many=True` unfortunately.
Thanks @cobang for his helps.

Add support for presentation_serializer="self"

---

MANIFEST.in
README.md
drf_extra_fields/fields.py
setup.py

Completed version of #84. Thanks @ybrs for the contribution.

Enhance Base64FileField

---

tox.ini

Django 3.0 and 3.1 are EOL, and 4.0 is the latest stable release now.
https://www.djangoproject.com/download/

Update Django versions to test

---

drf_extra_fields/fields.py
drf_extra_fields/geo_fields.py
drf_extra_fields/relations.py
requirements_dev.txt
tests/test_fields.py
tests/utils.py

* Applies `pyupgrade --py37-plus`
* Removed `mock` from `requirements_dev.txt` (replaced by unittest.mock)
* Simplify string formatting with a f-string

Modernize the code for Python 3.7

---

Dockerfile

Fixes #193
`tzdata` output with this update:
```
Setting up tzdata (2023c-0ubuntu0.22.04.1) ...
Current default time zone: 'Etc/UTC'
Local time is now:      Mon May 22 11:49:31 UTC 2023.
Universal Time is now:  Mon May 22 11:49:31 UTC 2023.
Run 'dpkg-reconfigure tzdata' if you wish to change it.
```

Prevent `tzdata` from asking for input and hanging

---

Dockerfile
drf_extra_fields/fields.py
requirements.txt
setup.py
tests/test_fields.py
tox.ini

This PR resolves #185 by replacing `imghdr` with the tiny and dependency free `filetype` module. The module was selected from the recommendations listed in PEP-594.
Additionally, tests have been extended to including Python 3.11 coverage in order to validate that this resolves the `DeprecationWarning`.
External references: [PEP-594](https://peps.python.org/pep-0594/#imghdr)

Remove Python 3.11 deprecation warning

---

drf_extra_fields/fields.py

Fixes #182.
It was trying to import `Pillow` even though `filetype` can detect the file type. The `If` condition is fixed.

Fallback to `Pillow` and try to import it only when necessary

---

drf_extra_fields/fields.py
tests/test_fields.py

This commit changes the way we open the file in the base64 encoding operation. Instead of using Python's built-in 'open' function with the file's path, we now utilize the 'open' method provided by the file object itself. This modification makes our code more flexible, enabling it to work with file-like objects that might not have a direct filesystem path.

Use built-in 'open' method for file object
